dist: xenial
sudo: false
language: go
addons:
  apt:
    packages:
    # needed for the nfpm pipe:
    - rpm
    # needed for the snap pipe:
    - snapcraft
env:
# needed for the snap pipe:
- PATH=/snap/bin:$PATH
go:
- 1.11.x
before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.10.2
install:
# needed for the snap pipe:
- sudo snap install snapcraft --classic
# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
script:
- golangci-lint run -v      # run a bunch of code checkers/linters in parallel
- go test -v -race ./...  # Run all the tests with the race detector enabled
notifications:
  email: false
